### ISSUE TITLE
Warning that unit is not available in faction is not using displayText

### ISSUE THREAD

**Issue by klauskopec** [achapin/homeworldfleetcommand-forcebuilder#20]
Fix is probably to use use "displayText[force.faction]" in the line mentioned below.

https://github.com/achapin/homeworldfleetcommand-forcebuilder/blob/f02317439b89754eb09f829794d04bcc40b252d8/hfcufb.js#L620

**Comment by achapin** [comment]
Fixed by #31 thanks to @klauskopec !
