### ISSUE TITLE
Scout Box Kadesh Mothership and Fuel Pod units have hand/play values

### ISSUE THREAD

**Issue by klauskopec** [achapin/homeworldfleetcommand-forcebuilder#9]
The Kadesh Mothership and Fuel Pod units have hand/play values usually only found on, e.g., faction cards and leaders. Please add these to the calculations. I'll provide the data in fields "hand" and "play" for these units like its done for leaders in my Scout Box data update PR.

**Comment by achapin** [comment]
Fixed, thanks @klauskopec !
